In [1]:
aList = ["John",33,"toronto",True]
print(aList)

['John', 33, 'toronto', True]


In [2]:
Mahasiswa = ["Muhammad Luthfi Pratama Putra",2020071008,"Informatika","DAA","15/09/2021","Universitas Pembangunan Jaya"]
print(Mahasiswa)

['Muhammad Luthfi Pratama Putra', 2020071008, 'Informatika', 'DAA', '15/09/2021', 'Universitas Pembangunan Jaya']


In [3]:
bin_colors=['Red','Green','Blue','Yellow']
bin_colors[1]

'Green'

In [4]:
Mahasiswa = ["Muhammad Luthfi Pratama Putra",2020071008,"Informatika","DAA","15/09/2021","Universitas Pembangunan Jaya"]
Mahasiswa[1]

2020071008

In [5]:
Mahasiswa = ["Muhammad Luthfi Pratama Putra",2020071008,"Informatika","DAA","15/09/2021","Universitas Pembangunan Jaya"]
Mahasiswa[5]

'Universitas Pembangunan Jaya'

In [6]:
bin_colors=['Red','Green','Blue','Yellow']
bin_colors[0:2]

['Red', 'Green']

In [7]:
Mahasiswa = ['Muhammad Luthfi Pratama Putra','2020071008','Informatika','DAA','15/09/2021','Universitas Pembangunan Jaya']
Mahasiswa[1:3]

['2020071008', 'Informatika']

In [8]:
bin_colors=['Red','Green','Blue','Yellow']
for aColor in bin_colors:
  print(aColor + " Square")

Red Square
Green Square
Blue Square
Yellow Square


In [9]:
Mahasiswa = ['Muhammad Luthfi Pratama Putra','2020071008','Informatika','DAA','15/09/2021','Universitas Pembangunan Jaya']
for aMahasiswa in Mahasiswa:
  print("UPJ " + aMahasiswa)

UPJ Muhammad Luthfi Pratama Putra
UPJ 2020071008
UPJ Informatika
UPJ DAA
UPJ 15/09/2021
UPJ Universitas Pembangunan Jaya


In [10]:
bin_colors=('Red','Green','Blue','Yellow')
bin_colors[1]

'Green'

In [ ]:
bin_colors[2:]

('Blue', 'Yellow')

In [11]:
UPJ=('Universitas','Pembagunan','Jaya')
UPJ[0:]

('Universitas', 'Pembagunan', 'Jaya')

In [12]:
nested_tuple=([100], [200,400,600], [300], [400,800])
print(nested_tuple)

([100], [200, 400, 600], [300], [400, 800])


In [13]:
bin_colors ={
    "manual_color": "Yellow",
    "approved_color": "Green",
    "refuse_color": "Red"
}
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refuse_color': 'Red'}


In [14]:
bin_colors.get('approved_color')

'Green'

In [15]:
bin_colors['approved_color']

'Green'

In [16]:
bin_colors['approved_color']="Purple"
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refuse_color': 'Red'}


In [17]:
Mahasiswa ={
    "Nama": "Muhammad Luthfi Pratama Putra",
    "NIM": "2020071008",
    "Prodi": "Informatika",
    "Universitas": "UPJ"
}
print(Mahasiswa)

{'Nama': 'Muhammad Luthfi Pratama Putra', 'NIM': '2020071008', 'Prodi': 'Informatika', 'Universitas': 'UPJ'}


In [18]:
green = {'grass', 'leaves'}
print(green)

{'leaves', 'grass'}


In [19]:
green = {'grass', 'leaves','leaves'}
print(green)

{'leaves', 'grass'}


In [20]:
yellow = {'fire hydrant', 'blood', 'rose', 'leaves'}
red = {'dandelions', 'fire hydrant', 'leaves'}
print(yellow | red)

{'fire hydrant', 'dandelions', 'leaves', 'blood', 'rose'}


In [21]:
yellow = {'fire hydrant', 'blood', 'rose', 'leaves'}
red = {'dandelions', 'fire hydrant', 'leaves'}
print(yellow & red)

{'fire hydrant', 'leaves'}


In [22]:
import pandas as pd
df = pd.DataFrame([['1', 'Fares', 32, True], ['2', 'Elena', 23, False], ['3', 'Steven', 40, True]])
df.columns = ['id', 'name', 'age', 'decision']
df

id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True

In [23]:
df[['name','age']]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [24]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [25]:
df.iloc[1:3,:]

id    name  age  decision
1  2   Elena   23     False
2  3  Steven   40      True

In [26]:
df[df.age>30]

id    name  age  decision
0  1   Fares   32      True
2  3  Steven   40      True

In [27]:
df[(df.age<35)&(df.decision==True)]

id   name  age  decision
0  1  Fares   32      True

In [28]:
import pandas as pd
df = pd.DataFrame([['1', 'Informatika', 50, 30, 20], ['2', 'Sistem Informasi', 55, 30, 25], ['3', 'Teknik Sipil', 40, 30, 10]])
df.columns = ['No', 'Prodi', 'Mahasiswa', 'Lakilaki', 'Perempuan']
df

No             Prodi  Mahasiswa  Lakilaki  Perempuan
0  1       Informatika         50        30         20
1  2  Sistem Informasi         55        30         25
2  3      Teknik Sipil         40        30         10

In [30]:
import numpy as np
myMatrix = np.array([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [31]:
print(type(myMatrix))

<class 'numpy.ndarray'>


In [32]:
import numpy as np
Matrix = np.array([[100, 200, 300],
                   [700, 600, 500],
                   [900, 1000, 800]])
print("Matrix: ")
print(Matrix)

transpose_matrix = np.transpose(Matrix)

print("Transpose Matrix: ")
print(transpose_matrix)

Matrix: 
[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]
Transpose Matrix: 
[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]


In [33]:
myVector = [22,33,44,55]
print(myVector)

[22, 33, 44, 55]


In [34]:
print(type(myVector))

<class 'list'>


In [35]:
myVector = np.array([22,33,44,55])
print(myVector)

[22 33 44 55]


In [36]:
print(type(myVector))

<class 'numpy.ndarray'>
